apiVersion: v1
kind: Pod
metadata:
  name: java-app-pod
  labels:
    app: java-app
spec:
  containers:
  - name: java-app-container
    image: rayanbha/stage:latest
    ports:
    - containerPort: 8080
    command: ["java", "-jar", "/Pidev3-1.0-SNAPSHOT.jar"]
